# Makefile pour lancer les tests avec behave
tests:	tests_ordreappel

tests_ordreappel:
	behave ordreappel-4-1.feature
	behave ordreappel-4-2.feature

tests_propositions:
	behave propositions-5-1-bmax.feature
	behave propositions-5-1-internat-1.feature
