convertall:	nb2py nb2html

nb2py:
	jupyter-nbconvert --to python ParcourSup.py_version_simplifiee.ipynb ParcourSup.py_simulation_utilisant_notre_implementation_complete.ipynb

nb2html:
	jupyter-nbconvert --to html ParcourSup.py_version_simplifiee.ipynb ParcourSup.py_simulation_utilisant_notre_implementation_complete.ipynb
